sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8
  
before_install:
  - uname -a
  - chmod +x pom.xml
  
script:
# since we run parallel tests using embedded mongodb in fresh environment all tests run first in parallel 
# will try to download the embedded mongo to this travis instance but the late ones will fail to write.
# We will therefore run one test using mongodb first that will download the mongo instance and
# then the rest of the test that will no longer need to download the embedded mongo since it will exist
  -  mvn -DsomeModule.test.includes="**/QueryServiceTest.java" test
  -  mvn -DsomeModule.test.excludes="**/QueryServiceTest.java" test
 
