sudo: required

language: java

jdk:
  - oraclejdk8
  
before_install:
  - chmod +x pom.xml
  
script:
  #-  mvn -DsomeModule.test.includes="**/UpStreamEventHandlerTest.java, **/TestExtractionHandler.java, **/ObjectHandlerTest.java, **/SubscriptionServiceTest.java" test
  -  mvn -DsomeModule.test.includes="**/ObjectHandlerTest.java" test
