sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8
  
before_install:
  - uname -a
  - chmod +x pom.xml
  
script:
  #-  mvn -DsomeModule.test.includes="**/UpStreamEventHandlerTest.java, **/TestExtractionHandler.java, **/ObjectHandlerTest.java, **/SubscriptionServiceTest.java" test
  #-  mvn -DsomeModule.test.includes="**/SubscriptionServiceTest.java, **/ObjectHandlerTest.java" test
  - mvn clean install
